import type { Scene } from "./_helpers";

export const splatWithPrimitives: Scene = {
  name: "Splat + Primitives",
  description:
    "A gaussian splat scene composed with standard 3D primitives and lights",
  spec: {
    root: "scene",
    elements: {
      scene: {
        type: "Group",
        props: { position: null, rotation: null, scale: null },
        children: [
          "camera",
          "ambient",
          "sun",
          "splat",
          "marker-left",
          "marker-right",
          "floor-plane",
          "grid",
          "label",
          "controls",
        ],
      },
      camera: {
        type: "PerspectiveCamera",
        props: {
          position: [4, 3, 6],
          rotation: null,
          scale: null,
          fov: 50,
          near: null,
          far: null,
          makeDefault: true,
        },
        children: [],
      },
      ambient: {
        type: "AmbientLight",
        props: { color: "#ffffff", intensity: 0.4 },
        children: [],
      },
      sun: {
        type: "DirectionalLight",
        props: {
          position: [8, 10, 5],
          rotation: null,
          scale: null,
          color: "#fff5e0",
          intensity: 2.5,
          castShadow: true,
        },
        children: [],
      },
      splat: {
        type: "GaussianSplat",
        props: {
          src: "https://huggingface.co/datasets/dylanebert/3dgs/resolve/main/garden/garden-7k.splat",
          position: [0, 0, 0],
          rotation: null,
          scale: [1, 1, 1],
          castShadow: null,
          receiveShadow: null,
          alphaHash: null,
          toneMapped: null,
          visible: true,
        },
        children: [],
      },
      "marker-left": {
        type: "Sphere",
        props: {
          position: [-2, 1.5, 0],
          rotation: null,
          scale: null,
          radius: 0.2,
          widthSegments: 16,
          heightSegments: 16,
          castShadow: true,
          receiveShadow: null,
          material: {
            color: "#ff4444",
            metalness: 0.8,
            roughness: 0.2,
            emissive: "#ff2222",
            emissiveIntensity: 0.5,
            opacity: null,
            transparent: null,
            wireframe: null,
          },
        },
        children: [],
      },
      "marker-right": {
        type: "Sphere",
        props: {
          position: [2, 1.5, 0],
          rotation: null,
          scale: null,
          radius: 0.2,
          widthSegments: 16,
          heightSegments: 16,
          castShadow: true,
          receiveShadow: null,
          material: {
            color: "#4488ff",
            metalness: 0.8,
            roughness: 0.2,
            emissive: "#2266ff",
            emissiveIntensity: 0.5,
            opacity: null,
            transparent: null,
            wireframe: null,
          },
        },
        children: [],
      },
      "floor-plane": {
        type: "Plane",
        props: {
          position: [0, -0.5, 0],
          rotation: [-1.5708, 0, 0],
          scale: null,
          width: 30,
          height: 30,
          castShadow: null,
          receiveShadow: true,
          material: {
            color: "#1a1a1a",
            metalness: 0.1,
            roughness: 0.9,
            emissive: null,
            emissiveIntensity: null,
            opacity: null,
            transparent: null,
            wireframe: null,
          },
        },
        children: [],
      },
      grid: {
        type: "GridHelper",
        props: {
          position: [0, -0.49, 0],
          rotation: null,
          scale: null,
          size: 30,
          divisions: 30,
          color1: "#333333",
          color2: "#1a1a1a",
        },
        children: [],
      },
      label: {
        type: "Text3D",
        props: {
          position: [0, 3, -2],
          rotation: null,
          scale: null,
          text: "Gaussian Splat",
          size: 0.3,
          height: 0.05,
          color: "#ffffff",
          font: null,
          letterSpacing: null,
          lineHeight: null,
          curveSegments: null,
          bevelEnabled: null,
          bevelThickness: null,
          bevelSize: null,
          castShadow: null,
          receiveShadow: null,
        },
        children: [],
      },
      controls: {
        type: "OrbitControls",
        props: {
          enableDamping: true,
          dampingFactor: null,
          enableZoom: null,
          enablePan: null,
          enableRotate: null,
          minDistance: 2,
          maxDistance: 20,
          minPolarAngle: 0.2,
          maxPolarAngle: 1.5,
          autoRotate: true,
          autoRotateSpeed: 0.3,
          target: [0, 0.5, 0],
        },
        children: [],
      },
    },
  },
};
