minimumReleaseAge: 2880
engineStrict: true
allowBuilds:
  '@google/genai': false
  "@mongodb-js/zstd": false
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  msw: false
  node-liblzma: false
  protobufjs: false
  sharp: false

packages:
  - "apps/*"
  - "examples/*"
  - "examples/stripe-app/*"
  - "packages/*"
  - "tests/*"
