packages:
  - "apps/web"
  - "packages/core"
  - "packages/react"
  - "packages/react-email"
  - "packages/codegen"
  - "packages/react-state"
  - "packages/eslint-config"
  - "packages/typescript-config"
  - "examples/react-email"
