/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as BuilderRouteImport } from "./routes/builder";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiSpecRouteImport } from "./routes/api.spec";

const BuilderRoute = BuilderRouteImport.update({
  id: "/builder",
  path: "/builder",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSpecRoute = ApiSpecRouteImport.update({
  id: "/api/spec",
  path: "/api/spec",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/builder": typeof BuilderRoute;
  "/api/spec": typeof ApiSpecRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/builder": typeof BuilderRoute;
  "/api/spec": typeof ApiSpecRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/builder": typeof BuilderRoute;
  "/api/spec": typeof ApiSpecRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$" | "/builder" | "/api/spec";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$" | "/builder" | "/api/spec";
  id: "__root__" | "/" | "/$" | "/builder" | "/api/spec";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  BuilderRoute: typeof BuilderRoute;
  ApiSpecRoute: typeof ApiSpecRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/builder": {
      id: "/builder";
      path: "/builder";
      fullPath: "/builder";
      preLoaderRoute: typeof BuilderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/spec": {
      id: "/api/spec";
      path: "/api/spec";
      fullPath: "/api/spec";
      preLoaderRoute: typeof ApiSpecRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BuilderRoute: BuilderRoute,
  ApiSpecRoute: ApiSpecRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
